### ISSUE TITLE
Crossfit week-29

### ISSUE THREAD

**Issue by TheBarbellCoder** [TheBarbellCoder/personal-CoupleGoals18-19-#1]
booked sessions

**Comment by TheBarbellCoder** [comment]
Had to cancel session on 17.07. due to unavailability of shoes.

**Comment by manchigantu** [comment]
Cancelled today’s session due to laziness! Hopefully I will go for this Friday session!

**Comment by TheBarbellCoder** [comment]
Did my first WOD in Hildesheim
