### ISSUE TITLE
Weight Tracker

### ISSUE THREAD

**Issue by manchigantu** [TheBarbellCoder/personal-CoupleGoals18-19-#4]
[WeightTracker.xlsx](https://github.com/TheBarbellCoder/personal-CoupleGoals18-19-/files/2212742/WeightTracker.xlsx)

**Comment by manchigantu** [comment]
Please update your weight on daily basis or weekly basis. 230 was my heaviest i.e., after dinner. New weight 225 is my current lowest weight in the morning after gulping a cup of coffee. :)

**Comment by TheBarbellCoder** [comment]
All done
